---
title: "Time Series Analysis of Home Sales"
author: "Joshua Jaeger"
date: "2022-12-31"
output: rmarkdown::github_document
---



```{r}
suppressWarnings(library(dplyr))
suppressWarnings(library(tsibble))
suppressWarnings(library(ggplot2))
suppressWarnings(library(lubridate))
suppressWarnings(library(tibble))
suppressWarnings(library(tsibbledata))
suppressWarnings(library(feasts))
suppressWarnings(library(fable))
```

```{r}
us_home_price <- read.csv("RawData/MSPUS.csv")
head(us_home_price)
us_home_price <- rename(us_home_price, Price = MSPUS)
```

```{r}
us_home_price <- us_home_price %>%
  mutate(DATE = yearquarter(DATE)) %>%
  as_tsibble(index=DATE)
```

```{r}
ggplot(us_home_price) +
  geom_line(aes(x=DATE, y=Price)) +
  labs(title = "Median US House Price", y= "Price", x=NULL) +
  theme_minimal()
```

```{r}
us_home_price %>%
  model(STL(Price ~
              trend() +
              season())) %>%
  components() %>%
  autoplot()
```

```{r}
us_cpi <- read.csv("RawData/CPIAUCNS.csv")
head(us_cpi)
us_cpi <- us_cpi %>%
  mutate(adjustedcpi = CPIAUCNS/us_cpi[1,2])
head(us_cpi)
```

```{r}
us_cpi <- us_cpi %>%
  mutate(DATE = yearquarter(DATE)) %>%
  as_tsibble(index=DATE)

inflation_prices <- inner_join(us_home_price, us_cpi, by= c("DATE" ="DATE"))

inflation_prices <- mutate(inflation_prices, adjusted_price = Price/adjustedcpi)
```

```{r}
ggplot(inflation_prices) +
  geom_line(aes(x=DATE, y=adjusted_price)) +
  labs(title = "Median US House Price (Inflation Adjusted)", y= "Inflation Adjusted Price", x=NULL) +
  theme_minimal()
```

```{r}
inflation_prices %>%
  model(STL(adjusted_price ~
              trend() +
              season())) %>%
  components() %>%
  autoplot()
```


```{r}
us_home_sales <- read.csv("RawData/HSN1F.csv") 
head(us_home_sales)
```

```{r}
us_home_sales <- us_home_sales %>%
  rename(Sales = HSN1F) %>%
  mutate(DATE = yearmonth(DATE)) %>%
  as_tsibble(index=DATE)
```

```{r}
autoplot(us_home_sales,Sales) +
  theme_minimal() +
  labs(title = "US Home Sales", x=NULL)
```

```{r}
us_home_sales %>%
  model(
    STL(Sales ~ 
          trend() +
          season())) %>%
  components() %>%
  autoplot() 
  
```



```{r}
us_mortgage_rates <- read.csv("RawData/MORTGAGE30US.csv") %>%
  mutate(DATE = yearmonth(DATE)) %>%
  as_tsibble(index=DATE)

```

```{r}
model_data <- left_join(us_home_sales,us_mortgage_rates, by= c("DATE" = "DATE")) 
model_data
```

```{r}
fit <- model_data %>%
  model(ARIMA(Sales ~ pdq(d = 0)))

report(fit)
```

```{r}
model_future <- new_data(model, 20) %>%
  mutate(MORTGAGE30US = 8.5)
fit %>%
  fabletools::forecast(model_future)

head(model_future) 
```

```{r}
fit %>%
  forecast(model_future)
```

